//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSuDungDichVu
    {
        public string MaChiTietSuDungDichVu { get; set; }
        public string MaCHiTietDichVu { get; set; }
        public double ChiSoCu { get; set; }
        public double ChiSoMoi { get; set; }
        public string ThoiGian { get; set; }
        public string NgayLap { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual ChiTietDichVu ChiTietDichVu { get; set; }
        public virtual ChiTietDichVu ChiTietDichVu1 { get; set; }
    }
}
