//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3___Motel_Management_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string MaHopDong { get; set; }
        public string MaNguoi { get; set; }
        public string MaPhongTro { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
        public double TienCoc { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual Nguoi Nguoi { get; set; }
        public virtual PhongTro PhongTro { get; set; }
    }
}
